#!/usr/bin/env php
<?php
error_reporting(E_ALL);

if (PHP_SAPI != 'cli') {
	print("Be wise, use command line\n");
	exit(1);
}

if (!defined('PHP_VERSION_ID') || PHP_VERSION_ID < 50500) {
	printf("Need PHP 5.5, current version is %s\n", PHP_VERSION);
	exit(1);
}

$options_short = "";
$options_long = array(
	"config:",
);
$options = getopt($options_short, $options_long);

set_include_path(get_include_path() . PATH_SEPARATOR
	. __DIR__ . '/src/' . PATH_SEPARATOR
	. __DIR__ . '/lib/' . PATH_SEPARATOR
);

spl_autoload_register(function($class_name) {
    require(str_replace('_', '/', $class_name) . '.class.php');
});

define('PHPIRC_VERSION', '0.5');
printf("
       _           _
 _ __ | |__  _ __ (_)_ __ ___
| '_ \| '_ \| '_ \| | '__/ __|
| |_) | | | | |_) | | | | (__
| .__/|_| |_| .__/|_|_|  \___|
|_|         |_|           v%s

", PHPIRC_VERSION);

@include(!empty($options['config']) ? $options['config'] : 'config.php');
if (!isset($config)) {
	print("Config missing, read the README\n");
	exit(1);
}

while (TRUE) {
	$irc = new phpirc($config);
	$tick = 100;
	while (TRUE) {
		usleep($tick);

		try {
			$irc->process();
		} catch (Exception $e) {
			printf("ERR: IRC connector process exception: %s\n", $e->getMessage());
			break;
		}
	}
	printf("Unexpected crash D: Reconnecting in 10 sec\n");
	sleep(10);
}
